# Generated by Django 4.2.9 on 2025-06-12 11:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(blank=True, editable=False, help_text='Private channel id', null=True)),
                ('is_sleep', models.BooleanField(default=False, help_text='включения/выключения бота')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=4095)),
                ('content', tinymce.models.HTMLField(help_text='Текст ответа')),
                ('cleaned_content', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Маска',
                'verbose_name_plural': 'Маски',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=63)),
                ('content', tinymce.models.HTMLField()),
                ('cleaned_content', models.TextField(blank=True, editable=False, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Телеграм команда',
                'verbose_name_plural': 'Телеграм команды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=63, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=63, null=True)),
                ('status', models.CharField(choices=[('member', 'Member'), ('administrator', 'Administrator'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Телеграм Группа',
                'verbose_name_plural': 'Телеграм Группы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=63, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=63, null=True)),
                ('last_name', models.CharField(blank=True, max_length=63, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='users', to='responder.telegramgroup')),
            ],
            options={
                'verbose_name': 'Телеграм Пользователь',
                'verbose_name_plural': 'Телеграм Пользователи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=4095, null=True)),
                ('message_id', models.BigIntegerField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='responder.telegramgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='responder.telegramuser')),
            ],
            options={
                'verbose_name': 'Телеграм Сообщения',
                'verbose_name_plural': 'Телеграм Сообщении',
                'ordering': ('-created_at',),
            },
        ),
    ]
