# Generated by Django 4.2.9 on 2025-06-13 18:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mask',
            options={'ordering': ('-created_at',), 'verbose_name': 'маску', 'verbose_name_plural': 'Маски'},
        ),
        migrations.AlterModelOptions(
            name='telegramcommand',
            options={'ordering': ('-created_at',), 'verbose_name': 'команду', 'verbose_name_plural': 'Телеграм команды'},
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Телеграм сообщения', 'verbose_name_plural': 'Телеграм Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ('-created_at',), 'verbose_name': 'телеграм пользователя', 'verbose_name_plural': 'Телеграм Пользователи'},
        ),
        migrations.AlterField(
            model_name='data',
            name='is_sleep',
            field=models.BooleanField(default=False, help_text='включения/выключения бота', verbose_name='Спящий режим'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='content',
            field=tinymce.models.HTMLField(help_text='Текст ответа', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='text',
            field=models.CharField(max_length=4095, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='telegramcommand',
            name='command',
            field=models.CharField(max_length=15, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telegramcommand',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='telegramcommand',
            name='description',
            field=models.CharField(max_length=63, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='telegramcommand',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='telegramcommand',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Файл ID'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='status',
            field=models.CharField(choices=[('member', 'Member'), ('administrator', 'Administrator'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked')], max_length=15, verbose_name='Статус бота в группе'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='responder.telegramgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_id',
            field=models.BigIntegerField(verbose_name='ID сообщении'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text',
            field=models.CharField(blank=True, max_length=4095, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='responder.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='responder.telegramgroup', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
