# Generated by Django 4.2.9 on 2025-06-14 03:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0002_alter_mask_options_alter_telegramcommand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), default=('hello', 'world'), size=None),
            preserve_default=False,
        ),
    ]
