# Generated by Django 4.2.9 on 2025-06-14 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0003_mask_text_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), blank=True, size=None),
        ),
    ]
