# Generated by Django 4.2.9 on 2025-06-14 07:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0005_alter_mask_created_at_alter_mask_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='cleaned_content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mask',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), blank=True, editable=False, size=None),
        ),
    ]
