# Generated by Django 4.2.9 on 2025-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0006_alter_mask_cleaned_content_alter_mask_text_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('question', models.CharField(editable=False, max_length=4095, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, editable=False, max_length=4095, null=True, verbose_name='<UNK>')),
                ('count', models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Самые частые вопросы и ответы',
                'verbose_name_plural': 'Самые частые вопросы и ответы',
                'ordering': ('-count',),
            },
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'телеграм пользователя', 'verbose_name_plural': 'Телеграм Пользователи'},
        ),
    ]
