# Generated by Django 4.2.9 on 2025-06-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0007_faq_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, editable=False, max_length=4095, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True, verbose_name='Имя пользователя группы'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='responder.telegramgroup', verbose_name='Группа'),
        ),
    ]
