# Generated by Django 4.2.9 on 2025-06-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0008_alter_faq_answer_alter_telegramgroup_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-count',), 'verbose_name': 'Аналитика', 'verbose_name_plural': 'Аналитика'},
        ),
    ]
