# Generated by Django 4.2.9 on 2025-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0009_alter_faq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='masks', to='responder.telegramgroup'),
        ),
        migrations.AlterField(
            model_name='data',
            name='channel_id',
            field=models.BigIntegerField(blank=True, editable=False, help_text='ID Канала для сохранения медиа файлов.', null=True, verbose_name='ID Канала'),
        ),
    ]
