# Generated by Django 4.2.9 on 2025-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0010_mask_groups_alter_data_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='is_marked',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
    ]
