# Generated by Django 4.2.9 on 2025-07-09 11:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0011_telegrammessage_is_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='replies',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.replymessage', verbose_name='message'),
        ),
    ]
