# Generated by Django 4.2.9 on 2025-07-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0012_replymessage_telegrammessage_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responder.replymessage', verbose_name='message'),
        ),
    ]
