# Generated by Django 4.2.9 on 2025-07-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0013_alter_telegrammessage_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='replies',
        ),
        migrations.AddField(
            model_name='replymessage',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='responder.telegrammessage'),
        ),
    ]
