# Generated by Django 4.2.9 on 2025-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0014_remove_telegrammessage_replies_replymessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replymessage',
            options={'verbose_name': 'Ответить'},
        ),
        migrations.AddField(
            model_name='replymessage',
            name='cleaned_text',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
