# Generated by Django 4.2.9 on 2025-07-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0015_alter_replymessage_options_replymessage_cleaned_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replymessage',
            options={'verbose_name': 'Ответить', 'verbose_name_plural': 'Ответить'},
        ),
    ]
