# Generated by Django 4.2.9 on 2025-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0016_alter_replymessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymessage',
            name='is_retry',
            field=models.BooleanField(default=False, verbose_name='Отправить заново'),
        ),
        migrations.AddField(
            model_name='replymessage',
            name='is_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Отправлено'),
        ),
    ]
