# Generated by Django 4.2.9 on 2025-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0017_replymessage_is_retry_replymessage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='answer',
            field=models.CharField(blank=True, max_length=4095, null=True, verbose_name='Ответ'),
        ),
    ]
