# Generated by Django 4.2.9 on 2025-07-17 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0019_telegrammessage_answer_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='answer_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, editable=False, null=True, size=None),
        ),
    ]
