# Generated by Django 4.2.9 on 2025-07-22 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0020_alter_telegrammessage_answer_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='groups',
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='mask',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RUB', 'Rub'), ('KZT', 'Kzt'), ('UZS', 'Uzs'), ('TJS', 'Tjs'), ('CNY', 'Cny'), ('GEL', 'Gel'), ('AMD', 'Amd'), ('ВСЕ ГРУППЫ', 'All')], max_length=31), blank=True, null=True, size=None),
        ),
    ]
