# Generated by Django 4.2.9 on 2025-07-22 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0021_remove_mask_groups_alter_telegrammessage_text_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RUB', 'RUB'), ('KZT', 'KZT'), ('UZS', 'UZS'), ('TJS', 'TJS'), ('CNY', 'CNY'), ('GEL', 'GEL'), ('AMD', 'AMD'), ('ВСЕ ГРУППЫ', 'ВСЕ ГРУППЫ')], max_length=31), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Фильтрованный текст'),
        ),
    ]
