# Generated by Django 4.2.9 on 2025-07-22 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0023_alter_telegrammessage_text_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='text_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Фильтрованный текст'),
        ),
    ]
