# Generated by Django 4.2.9 on 2025-12-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0025_alter_mask_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_team_lead',
            field=models.BooleanField(default=False, verbose_name='Является руководителем команды'),
        ),
    ]
