# Generated by Django 4.2.9 on 2025-12-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0028_statictext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chat_id', models.CharField(max_length=128, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('live_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('add_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('team_lead', models.CharField(blank=True, max_length=100, null=True)),
                ('recommend_user', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Не пройдено', 'Не пройдено'), ('В ожидании', 'В ожидании'), ('Верифицирован', 'Верифицирован'), ('Не верифицирован', 'Не верифицирован'), ('Архив', 'Архив')], max_length=50)),
                ('geo', models.TextField(blank=True, null=True)),
                ('worked_platform', models.TextField(blank=True, null=True)),
                ('recommendation_user_contact', models.TextField(blank=True, null=True)),
                ('additionally', models.TextField(blank=True, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('main_page_passport', models.ImageField(blank=True, null=True, upload_to='verification/')),
                ('registration_page_passport', models.ImageField(blank=True, null=True, upload_to='verification/')),
                ('additional_information_passport', models.ImageField(blank=True, null=True, upload_to='verification/')),
                ('round_video', models.FileField(blank=True, null=True, upload_to='verification/')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
