# Generated by Django 4.2.9 on 2025-12-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0029_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Все верификации',
                'verbose_name_plural': 'Все верификации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('responder.verification',),
        ),
        migrations.CreateModel(
            name='ArchivedVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('responder.verification',),
        ),
        migrations.CreateModel(
            name='CurrentVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Текущие верификации',
                'verbose_name_plural': 'Текущие верификации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('responder.verification',),
        ),
    ]
