# Generated by Django 4.2.9 on 2025-12-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0030_allverification_archivedverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAdminField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('nickname', 'Никнейм'), ('fullname', 'ФИО'), ('phone', 'Номер телефона')], default='text', max_length=50)),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fields', to='responder.verification')),
            ],
            options={
                'verbose_name': 'Дополнительное поле',
                'verbose_name_plural': 'Дополнительные поля',
            },
        ),
    ]
