# Generated by Django 4.2.9 on 2025-12-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0031_verificationadminfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_team_lead',
        ),
    ]
