# Generated by Django 4.2.9 on 2025-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0032_remove_telegramuser_is_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
