# Generated by Django 4.2.9 on 2025-12-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0033_verification_expires_at_verification_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='statictext',
            options={'verbose_name': 'Статический текст', 'verbose_name_plural': 'Статические тексты'},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name': 'Верификация', 'verbose_name_plural': 'Верификации'},
        ),
        migrations.AddField(
            model_name='verification',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='В черном списке'),
        ),
        migrations.AlterField(
            model_name='statictext',
            name='code',
            field=models.CharField(max_length=256, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='statictext',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='add_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный телефон'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='additional_information_passport',
            field=models.ImageField(blank=True, null=True, upload_to='verification/', verbose_name='Паспорт (дополнительная информация)'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='additionally',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='chat_id',
            field=models.CharField(max_length=128, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='geo',
            field=models.TextField(blank=True, null=True, verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='live_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='main_page_passport',
            field=models.ImageField(blank=True, null=True, upload_to='verification/', verbose_name='Паспорт (главная страница)'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='recommend_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рекомендовал'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='recommendation_user_contact',
            field=models.TextField(blank=True, null=True, verbose_name='Контакт рекомендателя'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='registration_page_passport',
            field=models.ImageField(blank=True, null=True, upload_to='verification/', verbose_name='Паспорт (страница регистрации)'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='round_video',
            field=models.FileField(blank=True, null=True, upload_to='verification/', verbose_name='Видео-круг'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('Не пройдено', 'Не пройдено'), ('В ожидании', 'В ожидании'), ('Верифицирован', 'Верифицирован'), ('Не верифицирован', 'Не верифицирован'), ('Архив', 'Архив')], max_length=50, verbose_name='Статус верификации'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='team_lead',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тимлид'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='worked_platform',
            field=models.TextField(blank=True, null=True, verbose_name='Рабочие платформы'),
        ),
    ]
