# Generated by Django 4.2.9 on 2026-01-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0034_alter_country_options_alter_statictext_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.CharField(choices=[('USER', 'Пользователь'), ('SUPPORT', 'Саппорт'), ('HEAD_SUPPORT', 'Хэд-Саппорт'), ('VERIFICATOR', 'Верификатор'), ('ADMIN', 'Администратор'), ('PAYMENT_MANAGER', 'Платёжный менеджер')], default='USER', max_length=64, verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='responder.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
