# Generated by Django 4.2.9 on 2026-01-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0035_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_work_time', models.DateTimeField()),
                ('finish_work_time', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='responder.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
