# Generated by Django 4.2.9 on 2026-01-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0036_workerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdata',
            name='finish_work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
