# Generated by Django 4.2.9 on 2026-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0037_alter_workerdata_finish_work_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
