# Generated by Django 4.2.9 on 2026-01-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0038_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('worker_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='responder.workerdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('resolved', 'Решено'), ('unresolved', 'Нерешённый')], default='new', max_length=32)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='responder.merchant')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='responder.workerdata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
