# Generated by Django 4.2.9 on 2026-01-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0039_workershiftreport_workerdispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='responder.merchant')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='responder.workershiftreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
