# Generated by Django 4.2.9 on 2026-01-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0040_workerissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdispute',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='responder.workershiftreport'),
        ),
    ]
