# Generated by Django 4.2.9 on 2026-01-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0042_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': 'Мерчант', 'verbose_name_plural': 'Мерчанты'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Проблема сотрудника', 'verbose_name_plural': 'Проблемы сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='workerdata',
            options={'verbose_name': 'Смена сотрудника', 'verbose_name_plural': 'Смены сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='workerdispute',
            options={'verbose_name': 'Диспут', 'verbose_name_plural': 'Диспуты'},
        ),
        migrations.AlterModelOptions(
            name='workerissue',
            options={'verbose_name': 'Проблема по смене', 'verbose_name_plural': 'Проблемы по сменам'},
        ),
        migrations.AlterModelOptions(
            name='workershiftreport',
            options={'verbose_name': 'Отчет по смене', 'verbose_name_plural': 'Отчеты по сменам'},
        ),
        migrations.AlterField(
            model_name='merchant',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Название мерчанта'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='responder.profile', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='workerdata',
            name='finish_work_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания смены'),
        ),
        migrations.AlterField(
            model_name='workerdata',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='responder.profile', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='workerdata',
            name='start_work_time',
            field=models.DateTimeField(verbose_name='Время начала смены'),
        ),
        migrations.AlterField(
            model_name='workerdispute',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество диспутов'),
        ),
        migrations.AlterField(
            model_name='workerdispute',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='responder.merchant', verbose_name='Мерчант'),
        ),
        migrations.AlterField(
            model_name='workerdispute',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='responder.workershiftreport', verbose_name='Отчет по смене'),
        ),
        migrations.AlterField(
            model_name='workerdispute',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('resolved', 'Решено'), ('unresolved', 'Нерешённый')], default='new', max_length=32, verbose_name='Статус диспута'),
        ),
        migrations.AlterField(
            model_name='workerissue',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='responder.merchant', verbose_name='Мерчант'),
        ),
        migrations.AlterField(
            model_name='workerissue',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='responder.workershiftreport', verbose_name='Отчет по смене'),
        ),
        migrations.AlterField(
            model_name='workerissue',
            name='text',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='workershiftreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий / проблема'),
        ),
        migrations.AlterField(
            model_name='workershiftreport',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Отчет отправлен'),
        ),
        migrations.AlterField(
            model_name='workershiftreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки отчета'),
        ),
        migrations.AlterField(
            model_name='workershiftreport',
            name='worker_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='responder.workerdata', verbose_name='Смена'),
        ),
    ]
