# Generated by Django 5.2 on 2026-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0044_alter_verification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('data', models.JSONField(verbose_name='Данные анкеты (snapshot)')),
            ],
            options={
                'verbose_name': 'Черные списки',
                'verbose_name_plural': 'Черный список',
            },
        ),
    ]
