# Generated by Django 5.2 on 2026-02-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0045_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='data',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='responder.telegramgroup', verbose_name='Название группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='verification',
            field=models.ManyToManyField(related_name='blacklists', to='responder.verification', verbose_name='Найденные профили'),
        ),
    ]
