# Generated by Django 5.2 on 2026-02-04 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0046_remove_blacklist_data_blacklist_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='telegramcommand',
            options={'ordering': ('-created_at',), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='telegramgroup',
            options={'ordering': ('-created_at',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='WorkerMerchantStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('new_count', models.PositiveIntegerField(default=0, verbose_name='Новые диспуты')),
                ('resolved_count', models.PositiveIntegerField(default=0, verbose_name='Решенные диспуты')),
                ('unresolved_count', models.PositiveIntegerField(default=0, verbose_name='Нерешенные диспуты')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_stats', to='responder.merchant', verbose_name='Мерчант')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stats', to='responder.workershiftreport', verbose_name='Отчет по смене')),
            ],
            options={
                'verbose_name': 'Статистика диспутов по мерчанту',
                'verbose_name_plural': 'Статистика диспутов по мерчантам',
                'unique_together': {('report', 'merchant')},
            },
        ),
    ]
