# Generated by Django 5.2 on 2026-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0047_alter_data_options_alter_telegramcommand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
