# Generated by Django 4.2.9 on 2025-06-12 11:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Название рекламы', max_length=255, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('cleaned_content', models.TextField(blank=True, editable=False, null=True)),
                ('task_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('percent', models.CharField(editable=False, max_length=15)),
                ('is_sent', models.BooleanField(default=False, editable=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='broadcast_templates', to='responder.telegramgroup')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('cleaned_content', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Шаблон Рекламы',
                'verbose_name_plural': 'Шаблон Рекламы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='telegram/%Y/%m/%d')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=15, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TemplateButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='Текст кнопки', max_length=31)),
                ('url', models.URLField(help_text='Ссылка перенаправлении, например: https://www.example.com')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_buttons', to='broadcast.broadcasttemplate')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='broadcasttemplate',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='broadcast_templates', to='broadcast.media'),
        ),
        migrations.CreateModel(
            name='BroadcastButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='Текст кнопки', max_length=31)),
                ('url', models.URLField(help_text='Ссылка перенаправлении, например: https://www.example.com')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_buttons', to='broadcast.broadcast')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='broadcast',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='broadcasts', to='broadcast.media'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='broadcast.broadcasttemplate'),
        ),
    ]
