# Generated by Django 4.2.9 on 2025-06-13 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0002_alter_mask_options_alter_telegramcommand_options_and_more'),
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ('-created_at',), 'verbose_name': 'рассылку', 'verbose_name_plural': 'Рассылка'},
        ),
        migrations.AlterModelOptions(
            name='broadcastbutton',
            options={'ordering': ('order',), 'verbose_name': 'кнопку', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AlterModelOptions(
            name='broadcasttemplate',
            options={'ordering': ('-created_at',), 'verbose_name': 'шаблон рассылки', 'verbose_name_plural': 'Шаблоны рассылок'},
        ),
        migrations.AlterModelOptions(
            name='templatebutton',
            options={'ordering': ('order',), 'verbose_name': 'кнопку', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Не нужно, если выбран шаблон', null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='broadcast_templates', to='responder.telegramgroup', verbose_name='Телеграм группы'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='is_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='medias',
            field=models.ManyToManyField(blank=True, help_text='Не нужно, если выбран шаблон', related_name='broadcasts', to='broadcast.media', verbose_name='Прикрепляемые файлы'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='percent',
            field=models.CharField(editable=False, max_length=15, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 10, 12, 864335, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='broadcast.broadcasttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='title',
            field=models.CharField(blank=True, help_text='Название', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broadcastbutton',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок расположении'),
        ),
        migrations.AlterField(
            model_name='broadcastbutton',
            name='text',
            field=models.CharField(help_text='Текст кнопки', max_length=31, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='broadcastbutton',
            name='url',
            field=models.URLField(help_text='Ссылка перенаправлении, например: https://www.example.com', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='broadcasttemplate',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='broadcasttemplate',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='broadcast_templates', to='broadcast.media', verbose_name='Прикрепляемые файлы'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='telegram/%Y/%m/%d', verbose_name='Медиа файл'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Файл ID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок расположении'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='templatebutton',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок расположении'),
        ),
        migrations.AlterField(
            model_name='templatebutton',
            name='text',
            field=models.CharField(help_text='Текст кнопки', max_length=31, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='templatebutton',
            name='url',
            field=models.URLField(help_text='Ссылка перенаправлении, например: https://www.example.com', verbose_name='Ссылка'),
        ),
    ]
