# Generated by Django 4.2.9 on 2025-06-14 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_alter_broadcast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 3, 45, 9, 793988, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
