# Generated by Django 4.2.9 on 2025-06-14 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0006_alter_broadcast_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 7, 28, 12, 333816, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
