# Generated by Django 4.2.9 on 2025-06-14 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0007_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastbutton',
            options={'ordering': ('order',), 'verbose_name': '', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AlterModelOptions(
            name='templatebutton',
            options={'ordering': ('order',), 'verbose_name': '', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 8, 24, 58, 713755, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
