# Generated by Django 4.2.9 on 2025-06-14 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0009_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 10, 11, 218255, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
