# Generated by Django 4.2.9 on 2025-06-15 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0010_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 21, 2, 9, 524844, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
