# Generated by Django 4.2.9 on 2025-07-08 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0011_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='check_groups',
            field=models.BooleanField(default=False, verbose_name='Выбрать все группы'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 10, 59, 38, 908194, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
