# Generated by Django 4.2.9 on 2025-07-08 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0012_broadcast_check_groups_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasttemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 13, 22, 13, 984939, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
