# Generated by Django 4.2.9 on 2025-07-09 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0013_broadcasttemplate_title_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='check_groups',
            field=models.BooleanField(default=False, help_text='Выбрать все группы, исключая “Archive”', verbose_name='Выбрать все группы'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 11, 39, 19, 923738, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
