# Generated by Django 4.2.9 on 2025-07-09 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0014_alter_broadcast_check_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 11, 49, 35, 59776, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
