# Generated by Django 4.2.9 on 2025-07-09 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0018_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 12, 5, 25, 420953, tzinfo=datetime.timezone.utc), verbose_name='Расписание'),
        ),
    ]
