# Generated by Django 4.2.9 on 2025-07-17 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0020_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Расписание'),
        ),
    ]
