# Generated by Django 4.2.9 on 2025-07-22 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0021_alter_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='check_groups',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='groups',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RUB', 'RUB'), ('KZT', 'KZT'), ('UZS', 'UZS'), ('TJS', 'TJS'), ('CNY', 'CNY'), ('GEL', 'GEL'), ('AMD', 'AMD'), ('ВСЕ ГРУППЫ', 'ВСЕ ГРУППЫ')], max_length=31), blank=True, default=list, null=True, size=None),
        ),
    ]
