# Generated by Django 4.2.9 on 2025-12-12 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0022_remove_broadcast_check_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RUB', 'RUB'), ('KZT', 'KZT'), ('UZS', 'UZS'), ('TJS', 'TJS'), ('CNY', 'CNY'), ('GEL', 'GEL'), ('AMD', 'AMD'), ('TRANSGRAN', 'TRANSGRAN'), ('ВСЕ ГРУППЫ', 'ВСЕ ГРУППЫ')], max_length=31), blank=True, default=list, null=True, size=None),
        ),
    ]
